### ISSUE TITLE
Roadmap to improved localization

### ISSUE THREAD

**Issue by CajunAvenger** [MagicSetEditorPacks/Full-Magic-Pack#10]
The way non-English languages are set up in MSE right now are not really conducive to actually using them, and they tend to fall laughably out of date cause its harder for me to keep them up. I wanna try to fix that.

1) Word list localization tag: Currently all word lists share the same tag, so the only way for the user to actually use the other languages is to edit their code to point at word_lists_fr etc instead. Separating these into distinct word-lists (word-list-type-en, word-list-type-fr, etc) should allow us to load each of them with just the Set option input.

2) Automate subtype translation: A big part of the effort here is just getting and arranging the translations of the 300+ subtypes for 10+ languages, but using mtgjson's other languages features should allow us to compile the majority of these much quicker. After the initial pull it may be easier to just add the new types manually since they tend to be added quite rarely.

3) More languages: I'd like to be able to support at least the same languages MTG does on the card language side. I'd also like to see mse-locales updated to match, but those do want native speakers more. That'll be open to PRs and I will probably bit by bit work on my own translations there that will hopefully get improved by their users if necessary. 

4) More localizations: MSE 2.2.0 gives us the ability to localize stylesheets and card fields (some of which are in a PR i need to get to reviewing soon >.>). Like the locale files this might be something I work on bits at a time and hope for native speakers to assist on if they need it. The keywords file is another odd one: Probably one that can be updated by me just ripping translations from Scryfall, but it's a considerable sized file that will need the user to edit files to access, as it doesn't have a workaround like word-lists do at present. Though @haganbmj has been working some magic on the executable, they may be able to add localization fields for keyword matching and reminder text? That'll likely be awhile before it before it becomes a high priority though.

**Comment by haganbmj** [comment]
So part of the problem I've noticed is that there are places with the UI translations overlap Magic package specific translations. The location of these is frustrating so ideally I'd want to see which of them can be pulled back into the main `magic.mse-game` package and how much needs to stay here.

https://github.com/MagicSetEditorPacks/Full-Magic-Pack/blob/029e06f6843980903ad321f208959b44956c87e9/data/en.mse-locale/locale#L883-L898

There are pain points there with keeping versions in sync.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
I've written a script that searches Scryfall for subtypes and their translations. Attached is the result.
The first line is the list of languages, separated by ;
Each subsequent line is a different subtype, written in all the languages, separated by ;
I used the "UNKNOWN" token for translations I couldn't find.
I can run the script again to update this list when needed.
I tried MTGJSON as well but the data seems pretty much identical to Scryfall's.

[Subtype Translations.txt](https://github.com/MagicSetEditorPacks/Full-Magic-Pack/files/10661570/Subtype.Translations.txt)

**Comment by CajunAvenger** [comment]
Hunted down as many Unknowns as i could and [transferred over to json. ](https://github.com/MagicSetEditorPacks/TypesLocalizer/blob/main/translations.json). Gotta assign race/class creature types still then its digging into auto-building the foreign word_lists using the english one as a template.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
I managed to scrape a few more translations by looking at the gatherer. I did not incorporate your finds in this file though, so be careful when overwriting.

[Subtype.Translations.txt](https://github.com/MagicSetEditorPacks/Full-Magic-Pack/files/10674123/Subtype.Translations.txt)

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
I've written a script that searches Scryfall and the Gatherer for keywords, their translations and reminder texts. Attached is the result.

The [Keyword.Translations.txt] file has the same structure as the [Subtype.Translations.txt] above.

I modified the [language] file in /magic.mse-game/ as follows:
 - Added missing languages in the "languages" map.
 - Added "supertype_separator" and "keyword_types" keys in the "languages" map.
 - Modified the "spanish_number", "portuguese_number" and "french_number" methods, and added corresponding methods for the other languages.
 - Added more methods used for keyword reminders.

The various [keywords_xx] files are the localized versions of the [keywords] file in /magic.mse-game/. They all use the exact same keyword modes and keyword parameter types, the only difference is that I have translated the names of the keyword parameter types, since they appear as hints on the card while the user is typing the keyword.

[keywords.zip](https://github.com/MagicSetEditorPacks/Full-Magic-Pack/files/10854065/keywords.zip)
